apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envoy-gateway-listener-context
  labels:
    {{- include "extension-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certificate-policy-viewer
subjects:
{{ .Values.clusterRoleBindings.subjects | toYaml }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envoy-gateway-listener-context-status
  labels:
    {{- include "extension-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certificate-policy-status-update
subjects:
{{ .Values.clusterRoleBindings.subjects | toYaml }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "extension-server.fullname" . }}
  labels:
    {{- include "extension-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "extension-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "extension-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
