# This rule is not used by the project envoy-extension-server-app itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gateway.giantswarm.io.giantswarm.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: envoy-extension-server-app
    app.kubernetes.io/managed-by: kustomize
  name: certificatepolicy-viewer-role
rules:
- apiGroups:
  - gateway.giantswarm.io.giantswarm.io
  resources:
  - certificatepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.giantswarm.io.giantswarm.io
  resources:
  - certificatepolicies/status
  verbs:
  - get
