apiVersion: v2
appVersion: 0.1.0
name: envoy-extension-server
description: Please add description
home: https://github.com/giantswarm/envoy-extension-server
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
version: 0.1.0
annotations:
  # Adapt to 'giantswarm' if this application is not to be deployed by customers
  io.giantswarm.application.audience: all
  # Adapt to 'true' if Giant Swarm takes responsibility for this app where it's deplyed
  io.giantswarm.application.managed: "false"
  # used through .Chart.Annotations . Please replace TEAM-NAME with your team's short name, e. g. 'shield'  for team-shield
  io.giantswarm.application.team: cabbage
